SELECT conname FROM pg_constraint WHERE conrelid = 'waitlist_entries'::regclass AND contype = 'f' AND confrelid = 'class_sessions'::regclass;
SELECT id, name, class_type FROM class_templates WHERE class_type IS NULL;
SELECT ct.id, ct.name, ct.instructor_id FROM class_templates ct LEFT JOIN instructors i ON ct.instructor_id = i.id WHERE ct.instructor_id IS NOT NULL AND i.id IS NULL;
SELECT cs.id, cs.starts_at, ct.name FROM class_sessions cs JOIN class_templates ct ON cs.template_id = ct.id WHERE ct.is_active = FALSE AND cs.starts_at > NOW() AND cs.status = 'scheduled';
SELECT id, starts_at, max_capacity, booked_count FROM class_sessions WHERE booked_count > max_capacity;
SELECT id, starts_at, status FROM class_sessions WHERE status = 'scheduled' AND ends_at < NOW() - INTERVAL '1 hour' ORDER BY ends_at DESC LIMIT 20;
SELECT id, starts_at, template_id FROM class_sessions WHERE instructor_id IS NULL AND status = 'scheduled' AND starts_at > NOW();
SELECT cs.id, cs.starts_at, cs.instructor_id FROM class_sessions cs LEFT JOIN instructors i ON cs.instructor_id = i.id WHERE cs.instructor_id IS NOT NULL AND i.id IS NULL;
SELECT b.id, b.user_id, b.session_id, b.status, cs.status AS session_status FROM bookings b JOIN class_sessions cs ON b.session_id = cs.id WHERE b.status = 'confirmed' AND cs.status = 'cancelled';
SELECT user_id, session_id, COUNT(*) AS cnt FROM bookings WHERE session_id IS NOT NULL GROUP BY user_id, session_id HAVING COUNT(*) > 1;
SELECT id, user_id, session_id, credits_spent FROM bookings WHERE credits_spent <= 0 AND status = 'confirmed';
SELECT cb.user_id, u.email, cb.credit_type, cb.balance FROM credit_balances cb JOIN users u ON cb.user_id = u.id WHERE cb.balance < 0;
SELECT DISTINCT b.user_id, u.email, b.credit_type FROM bookings b JOIN users u ON b.user_id = u.id LEFT JOIN credit_balances cb ON cb.user_id = b.user_id AND cb.credit_type = b.credit_type WHERE b.status = 'confirmed' AND cb.id IS NULL;
SELECT user_id, credit_type, COUNT(*) AS cnt FROM credit_balances GROUP BY user_id, credit_type HAVING COUNT(*) > 1;
SELECT id, user_id, type, amount, created_at FROM credit_transactions WHERE amount = 0;
SELECT ct.id, ct.user_id, ct.booking_id, ct.amount FROM credit_transactions ct WHERE ct.type = 'refund' AND ct.booking_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM credit_transactions ct2 WHERE ct2.booking_id = ct.booking_id AND ct2.type = 'debit');
SELECT id, user_id, session_id, offer_expires_at, status FROM waitlist_entries WHERE status = 'offered' AND offer_expires_at < NOW();
SELECT we.id, we.user_id, we.session_id, we.status, cs.status AS session_status FROM waitlist_entries we JOIN class_sessions cs ON we.session_id = cs.id WHERE we.status IN ('waiting', 'offered') AND cs.status = 'cancelled';
SELECT u.id, u.email, u.name FROM users u LEFT JOIN instructors i ON i.user_id = u.id WHERE u.role = 'instructor' AND u.deleted_at IS NULL AND i.id IS NULL;
SELECT i.id, u.email, u.role FROM instructors i JOIN users u ON i.user_id = u.id WHERE u.role != 'instructor';
SELECT u.id, u.email, um.status, um.ends_at FROM users u JOIN user_memberships um ON um.user_id = u.id WHERE u.deleted_at IS NOT NULL AND um.status = 'active';
SELECT u.id, u.email, b.id AS booking_id, cs.starts_at FROM users u JOIN bookings b ON b.user_id = u.id JOIN class_sessions cs ON cs.id = b.session_id WHERE u.deleted_at IS NOT NULL AND b.status = 'confirmed' AND cs.starts_at > NOW();
